
spring:
  datasource:
    url: jdbc:mysql://192.168.18.203/bpr?useSSL=false&useTimezone=UTC
    username: maplelps
    password: Maplecode@2022
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    mvc.pathmatch.matching-strategy: ant_path_matcher


  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialec

